version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - 13306:3306
    volumes:
      - ./docker/db/initdb.d/:/docker-entrypoint-initdb.d
      - ./docker/db/mariadb:/var/lib/mysql
      - ./docker/db/mariadb:/bitnami
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8808:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=${MARIADB_USER}
      - PMA_PASSWORD=${MARIADB_PASSWORD}
  app:
    build: docker/app-php
    ports:
      - '1080:80'
      - '10443:443'
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}
    volumes:
        - ./httpdocs:/var/www/localhost/htdocs
    depends_on:
      - mariadb